import cv2 #opencv, computer vision library, media pipe is by google
from cvzone.HandTrackingModule import HandDetector #import hand gesture, detecting landmarks
from directkeys import PressKey, ReleaseKey #press is when hand is pressed, open is when it is released
from directkeys import space_pressed #when space key is pressed on the keyboard, boolean, value returned is 1, if not pressed then 0 is returned
import time

detector=HandDetector(detectionCon=0.8, maxHands=1) #passing in parameters, probability represents confidence, high confidence means that it is absolutely sure

space_key_pressed=space_pressed

time.sleep(2.0) #sleep for 2 seconds, to ensure everything is processed fully and runs correctly

current_key_pressed = set()

video=cv2.VideoCapture(0) #initialsing video capture stream, 0 for default/in-built webcam
#publishes frames from webcam, 3 cameras connected
while True: #runs infintely
    ret,frame=video.read() #reading frames from webcam and store
    keyPressed = False
    spacePressed=False
    key_count=0
    key_pressed=0   
    hands,img=detector.findHands(frame)
    #object of hand detection, detector is object, execute that method on the frame,
    #detecting different hand frames and storing that in the hands variable
    cv2.rectangle(img, (0, 480), (300, 425),(50, 50, 255), -2) #drawing rectangle on hands
    cv2.rectangle(img, (640, 480), (400, 425),(50, 50, 255), -2) #pixel coordinates
    if hands:
        lmList=hands[0]
        fingerUp=detector.fingersUp(lmList) #how many fingers are raised, passing function, stores landmarks of hand
        print(fingerUp)
        if fingerUp==[0,0,0,0,0]: #all fingers are up
            cv2.putText(frame, 'Finger Count: 0', (20,460), cv2.FONT_HERSHEY_COMPLEX, 1, (255,255,255), 1, cv2.LINE_AA) #pixel coordinate
            cv2.putText(frame, 'Jumping', (440,460), cv2.FONT_HERSHEY_COMPLEX, 1, (255,255,255), 1, cv2.LINE_AA)
            PressKey(space_key_pressed)
            spacePressed=True
            current_key_pressed.add(space_key_pressed)
            key_pressed=space_key_pressed
            keyPressed = True
            key_count=key_count+1
        if fingerUp==[0,1,0,0,0]:
            cv2.putText(frame, 'Finger Count: 1', (20,460), cv2.FONT_HERSHEY_COMPLEX, 1, (255,255,255), 1, cv2.LINE_AA)
            cv2.putText(frame, 'Not Jumping', (420,460), cv2.FONT_HERSHEY_COMPLEX, 1, (255,255,255), 1, cv2.LINE_AA)
        if fingerUp==[0,1,1,0,0]:
            cv2.putText(frame, 'Finger Count: 2', (20,460), cv2.FONT_HERSHEY_COMPLEX, 1, (255,255,255), 1, cv2.LINE_AA)
            cv2.putText(frame, 'Not Jumping', (420,460), cv2.FONT_HERSHEY_COMPLEX, 1, (255,255,255), 1, cv2.LINE_AA)
        if fingerUp==[0,1,1,1,0]:
            cv2.putText(frame, 'Finger Count: 3', (20,460), cv2.FONT_HERSHEY_COMPLEX, 1, (255,255,255), 1, cv2.LINE_AA)
            cv2.putText(frame, 'Not Jumping', (420,460), cv2.FONT_HERSHEY_COMPLEX, 1, (255,255,255), 1, cv2.LINE_AA)
        if fingerUp==[0,1,1,1,1]:
            cv2.putText(frame, 'Finger Count: 4', (20,460), cv2.FONT_HERSHEY_COMPLEX, 1, (255,255,255), 1, cv2.LINE_AA)
            cv2.putText(frame, 'Not Jumping', (420,460), cv2.FONT_HERSHEY_COMPLEX, 1, (255,255,255), 1, cv2.LINE_AA)
        if fingerUp==[1,1,1,1,1]:
            cv2.putText(frame, 'Finger Count: 5', (20,460), cv2.FONT_HERSHEY_COMPLEX, 1, (255,255,255), 1, cv2.LINE_AA)
            cv2.putText(frame, 'Not Jumping', (420,460), cv2.FONT_HERSHEY_COMPLEX, 1, (255,255,255), 1, cv2.LINE_AA)
        if not keyPressed and len(current_key_pressed) != 0:
            for key in current_key_pressed:
                ReleaseKey(key)
            current_key_pressed = set()
        elif key_count==1 and len(current_key_pressed)==2:    
            for key in current_key_pressed:             
                if key_pressed!=key:
                    ReleaseKey(key)
            current_key_pressed = set()
            for key in current_key_pressed:
                ReleaseKey(key)
            current_key_pressed = set()
    cv2.imshow("Frame",frame)
    k=cv2.waitKey(1) #wait until 1 key is pressed
    if k==ord('q'):
        break #quit the window

video.release() #release window
cv2.destroyAllWindows() #destroy any window that was generated by the program
